# Uso: $rake
ComandoJISON = "jison formulario.jison -o formulario.js"

# Acción por defecto
task :default => :compile


desc "Compila la gramatica formulario.jison"
task :compile => %w{formulario.jison} do
    sh "#{ComandoJISON}"
end
